services:
    todo-db:
        image: postgres:18.0-alpine3.22
        container_name: todo_micro_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: todo_micro
            POSTGRES_PORT: 5432
        networks:
            - todo
        volumes:
            - todo_micro_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
    user-db:
        image: postgres:18.0-alpine3.22
        container_name: user_micro_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: user_micro
            POSTGRES_PORT: 5432
        networks:
            - user
        volumes:
            - user_micro_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
    redis:
        image: redis:alpine
        container_name: todo_micro_redis
        networks:
            - todo
        volumes:
            - todo_micro_redis_data:/data
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
            interval: 5s
            timeout: 5s
            retries: 5
    rabbitmq:
        image: rabbitmq:4.2.1-management-alpine
        networks:
            - todo
        ports:
            - "5672:5672"
            - "15672:15672"
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 10s
    api-gateway:
        build: ./client
        ports:
            - "3000:3000"
        networks:
            - todo
            - user
        depends_on:
            - todo-service
            - user-service
            - rabbitmq
        environment:
            TODO_SERVICE_TARGET: todo-service:8080
            USER_SERVICE_TARGET: user-service:8081
            RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    user-service:
        build: ./user
        networks:
            - user
        depends_on:
            user-db:
                condition: service_healthy
        command: sh -c "make db/migrations/up && ./user"
        environment:
            POSTGRES_HOST: user-db
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: user_micro
            POSTGRES_SSLMODE: disable
            JWT_SECRET: secret
            JWT_EXPIRATION_HOURS: 24
    todo-service:
        build: ./server
        networks:
            - todo
        depends_on:
            todo-db:
                condition: service_healthy
            redis:
                condition: service_healthy
        command: sh -c "make db/migrations/up && ./todo"
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_EXPIRATION: 300
            POSTGRES_HOST: todo-db
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: todo_micro
            POSTGRES_SSLMODE: disable
            RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    mutate-todo:
        build: ./mutate-todo
        networks:
            - todo
        depends_on:
            todo-db:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        environment:
            POSTGRES_HOST: todo-db
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: todo_micro
            POSTGRES_SSLMODE: disable
            RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
networks:
    user:
        driver: bridge
    todo:
        driver: bridge
volumes:
    todo_micro_data:
    user_micro_data:
    todo_micro_redis_data:
